START AT 2018-09-02T12:19:40.591087-05:00
Traceback (most recent call last):
  File "launcher.py", line 58, in __init__
    self.job = self._get_job()
  File "launcher.py", line 114, in _get_job
    return jobutil.Job(
NameError: name 'jobutil' is not defined

START AT 2018-09-02T12:20:06.236321-05:00
Traceback (most recent call last):
  File "launcher.py", line 59, in __init__
    self.job = self._get_job()
  File "launcher.py", line 117, in _get_job
    url=JOB_DB_API_URL,
NameError: name 'JOB_DB_API_URL' is not defined

START AT 2018-09-02T12:26:20.513953-05:00
Traceback (most recent call last):
  File "launcher.py", line 60, in __init__
    self.job = self._get_job()
  File "launcher.py", line 119, in _get_job
    source=self.data_source,
AttributeError: 'Script' object has no attribute 'data_source'

START AT 2018-09-02T13:57:52.844931-05:00
Traceback (most recent call last):
  File "launcher.py", line 67, in __init__
    self._set_path()
  File "launcher.py", line 67, in __init__
    self._set_path()
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T13:58:55.248417-05:00
Traceback (most recent call last):
  File "launcher.py", line 64, in __init__
    self.last_run_date = job.last_run_date()
NameError: name 'job' is not defined

START AT 2018-09-02T13:59:06.164692-05:00
Traceback (most recent call last):
  File "launcher.py", line 64, in __init__
    self.last_run_date = self.job.last_run_date()
AttributeError: 'Job' object has no attribute 'last_run_date'

START AT 2018-09-02T14:00:16.641244-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T14:03:44.303527-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 142, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '../transportation-data-publishing/transportation-data-publishing/knack_data_pub.py'

START AT 2018-09-02T14:04:21.232878-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 142, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '../transportation-data-publishing/transportation-data-publishing/knack_data_pub.py'

START AT 2018-09-02T14:05:00.655147-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 142, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '../transportation-data-publishing/transportation-data-publishing/knack_data_pub.py'

START AT 2018-09-02T14:05:53.479763-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 142, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '../transportation-data-publishing/transportation-data-publishing/knack_data_pub.py'

START AT 2018-09-02T14:05:59.195109-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 142, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '../transportation-data-publishing/transportation-data-publishing/knack_data_pub.py'

START AT 2018-09-02T14:06:24.210468-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 142, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '../transportation-data-publishing/transportation-data-publishing/knack_data_pub.py'

START AT 2018-09-02T14:07:04.006143-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 143, in _script_as_module
    spec.loader.exec_module(module)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 54, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 110, in dispatch_exception
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T14:15:24.589139-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 143, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 24, in <module>
    from config.knack.config import cfg
ModuleNotFoundError: No module named 'config.knack'

START AT 2018-09-02T14:15:37.855583-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 142, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 24, in <module>
    from config.knack.config import cfg
ModuleNotFoundError: No module named 'config.knack'

START AT 2018-09-02T14:16:26.224110-05:00
Traceback (most recent call last):
  File "launcher.py", line 68, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 142, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.knack.config import cfg
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.knack.config import cfg
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T14:26:23.881778-05:00
Traceback (most recent call last):
  File "launcher.py", line 63, in __init__
    self.job = self._get_job()
  File "launcher.py", line 123, in _get_job
    url=JOB_DB_API_URL,
NameError: name 'JOB_DB_API_URL' is not defined

START AT 2018-09-02T14:26:45.471547-05:00
Traceback (most recent call last):
  File "launcher.py", line 69, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 143, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.knack.config import cfg
ModuleNotFoundError: No module named 'config.knack'

START AT 2018-09-02T14:27:13.009943-05:00
START AT 2018-09-02T14:32:22.682487-05:00
Traceback (most recent call last):
  File "launcher.py", line 69, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 143, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.knack.config import cfg
ModuleNotFoundError: No module named 'config.knack'

START AT 2018-09-02T14:36:03.311880-05:00
Traceback (most recent call last):
  File "launcher.py", line 69, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 143, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.knack.config import cfg
ModuleNotFoundError: No module named 'config.knack'

START AT 2018-09-02T14:36:36.073329-05:00
Traceback (most recent call last):
  File "launcher.py", line 69, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 143, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.knack.config import cfg
ModuleNotFoundError: No module named 'config.knack'

START AT 2018-09-02T14:36:39.739752-05:00
Traceback (most recent call last):
  File "launcher.py", line 69, in __init__
  File "launcher.py", line 143, in _script_as_module
    # (see: https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.knack.config import cfg
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.knack.config import cfg
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T14:46:22.460818-05:00
Traceback (most recent call last):
  File "launcher.py", line 72, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 146, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.knack.config import cfg
ModuleNotFoundError: No module named 'config.knack'

START AT 2018-09-02T14:47:20.922922-05:00
Traceback (most recent call last):
  File "launcher.py", line 66, in __init__
    self.job = self._get_job()
  File "launcher.py", line 126, in _get_job
    url=secrets.JOB_DB_API_URL,
NameError: name 'secrets' is not defined

START AT 2018-09-02T14:47:53.123749-05:00
START AT 2018-09-02T14:53:06.114785-05:00
Traceback (most recent call last):
  File "launcher.py", line 72, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 147, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.secrets import *
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 25, in <module>
    from config.secrets import *
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T14:53:22.281345-05:00
START AT 2018-09-02T14:54:42.507149-05:00
START AT 2018-09-02T14:59:10.359434-05:00
START AT 2018-09-02T15:00:19.868479-05:00
START AT 2018-09-02T15:01:57.455763-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.job.result('success')
  File "launcher.py", line 82, in __init__
    self.job.result('success')
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 66, in dispatch_line
    self.user_line(frame)
bdb.BdbQuit

START AT 2018-09-02T15:02:44.245290-05:00
START AT 2018-09-02T15:03:24.379600-05:00
START AT 2018-09-02T15:04:07.303202-05:00
START AT 2018-09-02T15:04:53.183931-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 304, in main
    """
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 261, in cli_args
    #TODO add temporal filter / last_run_date arg (format?)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 261, in cli_args
    #TODO add temporal filter / last_run_date arg (format?)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T17:06:55.588076-05:00
Traceback (most recent call last):
  File "launcher.py", line 71, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 145, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 260
    WHY ARENT OYU HANDLING THE -d CORRECTLY????
            ^
SyntaxError: invalid syntax

START AT 2018-09-02T17:07:08.449017-05:00
Traceback (most recent call last):
  File "launcher.py", line 75, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 304, in main
    pdg.set_trace()
NameError: name 'pdg' is not defined

START AT 2018-09-02T17:07:26.821236-05:00
Traceback (most recent call last):
  File "launcher.py", line 75, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 306, in main
    auth = KNACK_CREDENTIALS[args.app_name]
NameError: name 'KNACK_CREDENTIALS' is not defined

START AT 2018-09-02T17:07:51.854668-05:00
Traceback (most recent call last):
  File "launcher.py", line 75, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 305, in main
    cfg_dataset = cfg[args.dataset]
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 305, in main
    cfg_dataset = cfg[args.dataset]
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T17:09:22.677027-05:00
Traceback (most recent call last):
  File "launcher.py", line 75, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 306, in main
    auth = KNACK_CREDENTIALS[args.app_name]
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 306, in main
    auth = KNACK_CREDENTIALS[args.app_name]
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T17:20:30.344516-05:00
Traceback (most recent call last):
  File "launcher.py", line 75, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 305, in main
    auth = KNACK_CREDENTIALS[args.app_name]
NameError: name 'KNACK_CREDENTIALS' is not defined

START AT 2018-09-02T17:20:56.673743-05:00
START AT 2018-09-02T17:31:20.658224-05:00
Traceback (most recent call last):
  File "launcher.py", line 71, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 145, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 24, in <module>
    from config.knack.config import cfg
ModuleNotFoundError: No module named 'config.knack'

START AT 2018-09-02T17:31:31.372186-05:00
Traceback (most recent call last):
  File "launcher.py", line 76, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 308, in main
    if not args.last_run_date or args.replace or job.destination == "csv":
AttributeError: 'Namespace' object has no attribute 'last_run_date'

START AT 2018-09-02T17:43:25.437430-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 310, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 256, in cli_args
    '--replace'
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/site-packages/tdutils/argutil.py", line 61, in get_parser
    arg_def = ARGUMENTS[arg_name]
KeyError: 'app_name--destination'

START AT 2018-09-02T17:44:03.991766-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 325, in main
    if cfg_dataset.get("multi_source"):
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 325, in main
    if cfg_dataset.get("multi_source"):
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T17:44:39.414755-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 325, in main
    if cfg_dataset.get("multi_source"):
NameError: name 'job' is not defined

START AT 2018-09-02T17:45:28.816849-05:00
START AT 2018-09-02T17:50:52.169835-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T17:51:16.008454-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T17:51:44.493130-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T17:53:13.964851-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T17:53:28.924930-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T17:53:39.533703-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T17:54:21.720877-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T17:54:27.528929-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T17:55:35.704166-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T17:56:05.206070-05:00
Traceback (most recent call last):
  File "launcher.py", line 77, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 77, in __init__
    self.module = self._script_as_module()
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T17:56:34.188832-05:00
Traceback (most recent call last):
  File "launcher.py", line 81, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T22:34:14.008659-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 289, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T22:34:22.934879-05:00
START AT 2018-09-02T22:34:54.500391-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 291, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T22:35:12.717984-05:00
START AT 2018-09-02T22:35:55.615884-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 291, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 267, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T22:37:40.745584-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 290, in main
    args = cli_args(args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 266, in cli_args
    parsed = parser.parse_args(args)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 1803, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/argparse.py", line 2089, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
TypeError: 'int' object is not subscriptable

START AT 2018-09-02T22:39:39.127447-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 291, in main
    args = cli_args(args)
NameError: name 'job' is not defined

START AT 2018-09-02T22:39:54.354780-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 294, in main
    if not args.last_run_date or args.replace or job.destination == "csv":
NameError: name 'job' is not defined

START AT 2018-09-02T22:41:04.519960-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 309, in main
    last_run_date, cfg_dataset["modified_date_field_id"]
UnboundLocalError: local variable 'last_run_date' referenced before assignment

START AT 2018-09-02T22:41:58.703052-05:00
START AT 2018-09-02T22:42:29.661785-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 294, in main
    if not args.last_run_date or args.replace:
UnboundLocalError: local variable 'last_run_date' referenced before assignment

START AT 2018-09-02T22:44:48.062220-05:00
START AT 2018-09-02T22:45:18.351320-05:00
START AT 2018-09-02T22:45:57.877304-05:00
Traceback (most recent call last):
  File "launcher.py", line 82, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 297, in main
    auth = KNACK_CREDENTIALS[args.app_name]
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 297, in main
    auth = KNACK_CREDENTIALS[args.app_name]
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T22:46:46.493467-05:00
Traceback (most recent call last):
  File "launcher.py", line 90, in __init__
    self.job.result('success', records_processed)
NameError: name 'records_processed' is not defined

START AT 2018-09-02T22:47:51.779329-05:00
Traceback (most recent call last):
  File "launcher.py", line 91, in __init__
    self.job.result('success', records_processed)
NameError: name 'records_processed' is not defined

START AT 2018-09-02T22:48:16.357725-05:00
START AT 2018-09-02T22:48:49.894515-05:00
START AT 2018-09-02T22:58:51.681602-05:00
START AT 2018-09-02T22:59:16.393239-05:00
START AT 2018-09-02T23:20:32.886908-05:00
Traceback (most recent call last):
  File "launcher.py", line 80, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 163, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 23, in <module>
    import _setpath
ModuleNotFoundError: No module named '_setpath'

START AT 2018-09-02T23:21:27.644759-05:00
Traceback (most recent call last):
  File "launcher.py", line 80, in __init__
    self.module = self._script_as_module()
  File "launcher.py", line 163, in _script_as_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 24, in <module>
    from config.knack.config import cfg
ModuleNotFoundError: No module named 'config.knack'

START AT 2018-09-02T23:21:49.616673-05:00
START AT 2018-09-02T23:24:44.828600-05:00
Traceback (most recent call last):
  File "launcher.py", line 73, in __init__
    self._clear_module_cache(['congig', 'config.secrets'])
TypeError: _clear_module_cache() takes 1 positional argument but 2 were given

START AT 2018-09-02T23:28:31.793511-05:00
Traceback (most recent call last):
  File "launcher.py", line 73, in __init__
    self._clear_module_cache(['config', 'config.secrets'])
TypeError: _clear_module_cache() takes 1 positional argument but 2 were given

START AT 2018-09-02T23:28:58.750928-05:00
Traceback (most recent call last):
  File "launcher.py", line 73, in __init__
    self._clear_module_cache(module_list=['config', 'config.secrets'])
TypeError: _clear_module_cache() got multiple values for argument 'module_list'

START AT 2018-09-02T23:29:51.743918-05:00
START AT 2018-09-02T23:36:42.995605-05:00
START AT 2018-09-02T23:37:38.915482-05:00
START AT 2018-09-02T23:39:30.150014-05:00
Traceback (most recent call last):
  File "launcher.py", line 80, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 301, in main
    if not last_run_date or args.replace:
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 301, in main
    if not last_run_date or args.replace:
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T23:39:47.518035-05:00
Traceback (most recent call last):
  File "launcher.py", line 80, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 301, in main
    print('thenextline')
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 301, in main
    print('thenextline')
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T23:40:07.083529-05:00
Traceback (most recent call last):
  File "launcher.py", line 80, in __init__
    self.results = self.main(self.args)
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 301, in main
    # replace dataset by setting the last run date to a long, long time ago
  File "../transportation-data-publishing/transportation-data-publishing/open_data/knack_data_pub.py", line 301, in main
    # replace dataset by setting the last run date to a long, long time ago
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/claryj/miniconda2/envs/dropbox/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

START AT 2018-09-02T23:40:31.427443-05:00
